### ISSUE TITLE
java version to 17 in 01-k8s-demo example

### ISSUE THREAD

**Issue by keunsoopark** [cognitedata/cdf-sdk-java-examples#18]
I think Java version should be fixed to 17, not 11 in 01-k8s-demo example - [ref](https://github.com/cognitedata/cdf-sdk-java-examples/blob/f5e598ce08e67e6a8e9f70ea0682a7fd905c8248/01-k8-demo/skaffold.yaml#L12) - to make sense with Java 17 instruction.

**Comment by kjetilh33** [comment]
Fixed
